CREATE DATABASE IF NOT EXISTS DMUCLUB;

USE DMUCLUB;

CREATE TABLE IF NOT EXISTS member(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(255) NOT NULL
);
